### ISSUE TITLE
Tab bar scroll performance in createMaterialTopNavigator

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/tabs#33] opened 2018-06-21 19:20 UTC
Repost from https://github.com/react-navigation/react-navigation/issues/4543

### Current Behavior

When using `createMaterialTopTabNavigator` with swipe and scroll enabled, the tab bar scrolling/swiping performance is very poor. The tab bar does not smoothly scroll with the screen.
See:
https://snack.expo.io/SkeF0iuZ7

This is even more evident in Debug mode or on slow devices.

### Expected Behavior

Compare that to the old behaviour in v1 with the `TabBarTop` component with `tabBarPosition: 'top'` in the `TabNavigator`, where the tab bar smoothly scrolls (on swipe) with the screen:
See:
https://snack.expo.io/HkEYpiuWm

### How to reproduce

New v2 behavior: https://snack.expo.io/SkeF0iuZ7
Old v1 behavior: https://snack.expo.io/HkEYpiuWm

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.4.1
| react-native     | 0.55.4

**Comment by brentvatne** [comment] 2018-06-21 19:20
@paulpopiel are you experiencing this on iOS or Android?

**Comment by paulpopiel** [comment] 2018-06-25 02:53
Thanks for moving it to the relevant repo. 

Experiencing on both platforms. It's not a breaking issue, but it is noticeable.

**Comment by zzq0826** [comment] 2018-09-13 13:12
I also encountered this problem.

**Comment by linux08** [comment] 2018-09-30 19:14
Hi @paulpopiel  issue still persist, Were you able to find a way around it?

**Comment by brentvatne** [comment] 2018-10-01 19:09
@satya164 - any idea what may have caused this reported regression?

**Comment by satya164** [comment] 2018-10-01 19:28
Since values don't support subscription after `Animated.add`, I have to add multiple listeners to subscribe to the value, which might be the cause. I don't think there's a straightforward fix since I can't use native driver here.

**Comment by elirangoshen** [comment] 2019-04-10 10:09
i notice it performs slow as well in my android.
react-native 0.59.2 
react-navigtaion-tabs 2.1.0

**Comment by brentvatne** [comment] 2019-04-12 17:28
@satya164 - is there anything we could push up into reanimated to make that better?

**Comment by satya164** [comment] 2019-04-12 17:34
@brentvatne I'll think about it

**Comment by satya164** [comment] 2019-05-19 18:41
The scrolling of tab bar is different in the latest version and this should no longer be an issue. Closing it.

**Closed by satya164** 2019-05-19 18:41 UTC
