### ISSUE TITLE
Display bottomtabnavigator on non included screens

### ISSUE THREAD

**Issue by max21** [react-navigation/tabs#196] opened 2019-10-16 17:15 UTC
### Current behaviour
When createBottomTabNavigator all screens with the bottom tab bar are in the bottom stack 

### Expected behaviour

I want to create a screen with the bottom stack but not include in the bottom stack. So the bottom stack can have no tab selected.
Like this example https://snack.expo.io/SyZElPlSm when you click on "Go to setting tab", the bottom tab is display but no tabs are selected.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by tamurhaq** [comment] 2019-10-19 01:32
I'm also trying to figure out this exact problem. I thought maybe including the screen the in bottomtabnavigator but somehow hiding the tab item could do it but so far that's not the way to go.

**Comment by tamurhaq** [comment] 2019-10-19 01:55
Ok, I think I've got it.

Let's say you want screens A, B and C on the bottom navigator. But you want to include the bottom navigator on screen D.

The way I got it done is by creating a stackNavigator with screens A and D. Include this as a screen in the bottom navigator instead of screen A. Now clicking that gives me screen A as intended but if I navigate to screen D I see the bottom navigator.

`
const HomeStack = createStackNavigator({
  A: { screen: A},
  D: { screen: D},
});
`

`export default createBottomTabNavigator(
  {
    A: { screen: HomeStack },
    B: { screen: B },    
    C: { screen: C },
  },`

This works for me.

**Comment by max21** [comment] 2019-10-20 12:15
Hi,
Yes it works for me too :)
And do you managed not to highlight the tab when you are on screen D ?

**Comment by satya164** [comment] 2019-10-20 13:47
This won't be supported in the library. It seems very confusing UX to be inside a tab but not highlight where you are.

**Closed by satya164** 2019-10-20 13:47 UTC

**Comment by max21** [comment] 2019-10-20 14:57
I've found a workaround : 

`    defaultNavigationOptions: ({navigation}) => ({
      tabBarButtonComponent: props => {
        return (navigation.state.routeName === 'Connect') ? null : <TouchableOpacity {...props} />;
      }
    }),`

When 'Connect' is the screen you don't want to see in bottom tab bar
